;Draw the tree illustrating the process generated by the count-change procedure of
;section 1.2.2 in making change for 11 cents. What are the orders of growth of
;the space and number of steps used by this process as the amount to be changed increases?

;It can easily be seen that there's a lot of repetition here-- for example, (cc 6 1)
; and all of its recurive steps are calculated at least twice.

; Bill the lizard shows here: http://www.billthelizard.com/2009/12/sicp-exercise-114-counting-change.html
; that the order of growth in terms of steps is equal to O(n^y) where y is the number
; of kinds-of-coins. This makes sense if you look at my diagram too-- you can see that for each
; kinds-of-coins value, (i.e. 5, 4, 3, 2, 1) there seems to be an entire sub-tree of recursive calls,
; within which many of the same calculations are repeated.
