;The sine of an angle (specified in radians) can be computed by making
;use of the approximation sin(x)=x if x is sufficiently small,
;and the trigonometric identity
;
;sin⁡(x)=3*sin⁡(x/3)−4*sin^3⁡(x/3)
;
;to reduce the size of the argument of sin. (For purposes of this exercise an angle
;  is considered “sufficiently small” if its magnitude is not greater than 0.1 radians.)
;
;These ideas are incorporated in the following procedures:
;How many times is the procedure p applied when (sine 12.15) is evaluated?
;
;What is the order of growth in space and number of steps (as a function of a)
;used by the process generated by the sine procedure when (sine a) is evaluated?


(define (cube x) (* x x x))

(define (p x) (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
   (if (not (> (abs angle) 0.1))
       angle
       (p (sine (/ angle 3.0)))))

(sine 12.15)
(if (not (> (abs 12.15) 0.1))
    12.15
    (p (sine (/ 12.15 3.0)))))  ;#1
        (sine 4.05)
        (if (not (> (abs 4.05) 0.1))
            4.05
            (p (sine (/ 4.05 3.0)))))  ;#2
          (sine 1.35)
            (if (not (> (abs 1.35) 0.1))
                1.35
                (p (sine (/ 1.35 3.0)))))   ;#3
            (sine 0.45)
              (if (not (> (abs 0.45) 0.1))
                  0.45
                  (p (sine (/ 0.45 3.0))))) ;#4
              (sine 0.15)
                (if (not (> (abs 0.15) 0.1))
                    0.15
                    (p (sine (/ 0.15 3.0)))))   ;#5
                (sine 0.05)
                (if (not (> (abs 0.05) 0.1))
                    0.05
                    (p (sine (/ 0.05 3.0))))) ;doesn't need to evaluate
                    = 0.05
(p (p (p (p (p (sine 0.05))))))

;How many times is the procedure p applied when (sine 12.15) is evaluated?
; 5 times

;What is the order of growth in space and number of steps (as a function of a)
;used by the process generated by the sine procedure when (sine a) is evaluated?
; Θ(log(n))
